MyEventCalendar/Models/BootstrapModel.cs
namespace MyEventCalendar.Models
{
    public class BootstrapModel
    {
        public string ID { get; set; }
        public string AreaLabeledId { get; set; }
        public ModalSize Size { get; set; }
        public string Message { get; set; }
        public string ModalSizeClass
        {
            get
            {
                switch (this.Size)
                {
                    case ModalSize.Small:
                        return "modal-sm";
                    case ModalSize.Large:
                        return "modal-lg";
                    case ModalSize.Medium:
                    default:
                        return "";
                }
            }
        }      
    }
}

MyEventCalendar/Models/Calendar/DayViewModel.cs
using System;

namespace MyEventCalendar.Models.Calendar
{
    public class DayViewModel
    {
        public DateTime DateTime { get; set; }
        public string Date { get; set; }
        public string DateStr { get; set; }
        public int DtDay { get; set; }
        public int? DayColumn { get; set; }
        public bool IsDayInCurrentMonth { get; set; }
        public bool HasEvent { get; set; }
        public string ShortDescription { get; set; }
    }
}

MyEventCalendar/Models/Calendar/WeekForMonthViewModel.cs
using System.Collections.Generic;

namespace MyEventCalendar.Models.Calendar
{
    public class WeekForMonthViewModel
    {
        public WeekForMonthViewModel()
        {
            Weeks = new List<List<DayViewModel>>();
        }
        public List<List<DayViewModel>> Weeks { get; set; }
        public int CurrentMonth { get; set; }
        public int CurrentYear { get; set; }
        public string NextMonth { get; set; }
        public string PrevMonth { get; set; }
        public string EventTitle { get; set; }
        public string EventDescription { get; set; }
    }
}

MyEventCalendar/Models/EventDbContext.cs
using System.Data.Entity;

namespace MyEventCalendar.Models
{
    public class EventDbContext:DbContext
    {
        public EventDbContext() : base("EventConnection")
        {
            Configuration.LazyLoadingEnabled = false;
        }
        public DbSet<EventModel> EventModels { get; set; }
    }
}

MyEventCalendar/Models/EventModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyEventCalendar.Models
{
    public class EventModel
    {
        [Key]
        public int ID { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
    }
}

MyEventCalendar/Models/ModalFooter.cs
namespace MyEventCalendar.Models
{
    public class ModalFooter
    {
        public string SubmitButtonText { get; set; } = "Submit";
        public string CancelButtonText { get; set; } = "Cancel";
        public string SubmitButtonID { get; set; } = "btn-submit";
        public string CancelButtonID { get; set; } = "btn-cancel";
        public bool OnlyCancelButton { get; set; }
    }
}

MyEventCalendar/Models/ModalHeader.cs
namespace MyEventCalendar.Models
{
    public class ModalHeader
    {
        public string Heading { get; set; }
    }
}

MyEventCalendar/Models/ModalSize.cs
namespace MyEventCalendar.Models
{
    public enum ModalSize
    {
        Small,
        Large,
        Medium
    }
}

MyEventCalendar/Controllers/CalendarController.cs
using System;
using System.Web.Mvc;
using MyEventCalendar.Repository;

namespace MyEventCalendar.Controllers
{
    public class CalendarController : Controller
    {
        private readonly IEventRepository _eventRepository;

        public CalendarController(IEventRepository eventRepository)
        {
            _eventRepository = eventRepository;
        }

        // GET: Calendar
        public ActionResult Index()
        {
            var model =_eventRepository.GetCalendar(DateTime.Now.Month, DateTime.Now.Year);
            return View(model);
        }

        /// <summary>
        /// Load next month or Previous month
        /// </summary>
        /// <param name="month"></param>
        /// <param name="year"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult LoadCalendarAjax(int month, int year)
        {
            var model = _eventRepository.GetCalendar(month, year);
            return PartialView("_Calendar", model);
        }
    }
}

MyEventCalendar/Controllers/EventController.cs
using System;
using System.Web.Mvc;
using MyEventCalendar.Models;
using MyEventCalendar.Repository;

namespace MyEventCalendar.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventRepository _eventRepository;

        public EventController(IEventRepository eventRepository)
        {
            _eventRepository = eventRepository;
        }

        // GET: Event
        public ActionResult ShowEvent()
        {
            return View(_eventRepository.GetAllEvent());
        }

        [HttpGet]
        public PartialViewResult AddEditEvent(int? id)
        {
            var model= new EventModel();
            if (id.HasValue)
            {
                var item = _eventRepository.GetEventById(id.Value);
                model.Date = item.Date;
                model.ShortDescription = item.ShortDescription;
                model.LongDescription = item.LongDescription;
            }

            return PartialView("~/Views/Event/_AddEditEvent.cshtml", model);
        }

        [HttpPost]
        public ActionResult AddEditEvent(int? id, EventModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isNew = !id.HasValue;
                    EventModel item = isNew ? new EventModel() : _eventRepository.GetEventById(id.Value);
                    item.Date = model.Date;
                    item.LongDescription = model.LongDescription;
                    item.ShortDescription = model.ShortDescription;
                    if (isNew)
                    {
                        _eventRepository.AddNewEvent(item);
                    }
                    else
                    {
                        _eventRepository.UpdateEvent(item);
                    }
                }

                return RedirectToAction("ShowEvent");
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpGet]
        public PartialViewResult DeleteEvent(int id)
        {
            EventModel item = _eventRepository.GetEventById(id);
            EventModel model= new EventModel()
            {
                ShortDescription = item.ShortDescription
            };
            return PartialView("~/Views/Event/_DeleteEvent.cshtml", model);
        }

        public ActionResult DeleteEvent(int id, FormCollection form)
        {
            var item = _eventRepository.GetEventById(id);
            _eventRepository.DeleteEvent(item);
            return RedirectToAction("ShowEvent");
        }
    }
}

MyEventCalendar/Views/Calendar/Index.cshtml
@model MyEventCalendar.Models.Calendar.WeekForMonthViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CalendarLayout.cshtml";
}
<style type="text/css">

    .ellipsis {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>
<div class="internship-calender-main" style="margin-top: 100px">
    <div class="container">
        <div class="content-calender" id="dvCalendar">
            @{
                Html.RenderPartial("_Calendar", Model);
            }
        </div>
    </div>
</div>
@Html.ActionLink("List", "ShowEvent", "Event", new { area = "" }, new { @class = "navbar-brand" })

<script type="text/javascript">
        function loadCalendar(date, id) {
            var month = 0;
            var year = 0;
            if (date != null) {
                month = date.split("/")[0];
                year = date.split("/")[1];
            }
            $.ajax({
                url: '@Url.Action("LoadCalendarAjax","Calendar")',
                data: {
                    month: month,
                    year: year,
                    id: id
                },
                success: function(data) {
                    $('#dvCalendar').html(data);
                },
                error: function(err) {
                    console.log(err.Text);
                }
            });
        }
</script>

MyEventCalendar/Views/Calendar/_Calendar.cshtml
@using System.Globalization


@{
    var prevMonth = 0;
    if (Model.PrevMonth.Split('/')[0] != "")
    {
        prevMonth = Convert.ToInt32(Model.PrevMonth.Split('/')[0]);
    }

    var nextMonth = 0;
    if (Model.NextMonth.Split('/')[0] != "")
    {
        nextMonth = Convert.ToInt32(Model.NextMonth.Split('/')[0]);
    }
}
<div class="month-year">
    <div class="calender-month-wrap">
        <ul>
            <li class="calender-month">@CultureInfo.CurrentCulture.DateTimeFormat.GetAbbreviatedMonthName(prevMonth)</li>
            <li class="calender-month calender-month-active">@CultureInfo.CurrentCulture.DateTimeFormat.GetAbbreviatedMonthName(Model.CurrentMonth)</li>
            <li class="calender-month">@CultureInfo.CurrentCulture.DateTimeFormat.GetAbbreviatedMonthName(nextMonth)</li>
        </ul>
    </div>
    <div class="calender-year">
        <p>@Model.CurrentYear</p>
    </div>
</div>
<div class="wrap-content-calendar-day-of-month">
    <div class="content-calendar-day-of-month caledar-active">
        <div class="day-of-week ">
            <ul>
                <li class="text-center">MON</li>
                <li class="text-center">TUE</li>
                <li class="text-center">WED</li>
                <li class="text-center">THU</li>
                <li class="text-center">FRI</li>
                <li class="text-center">SAT</li>
                <li class="text-center">SUN</li>
            </ul>
        </div>
        <div class="calendar-day">
            <ul>
                @foreach (var week in Model.Weeks)
                {
                    foreach (var item in week)
                    {
                        if (item != null)
                        {
                            if (item.DtDay > 0 && item.IsDayInCurrentMonth)
                            {
                                <li class="day-in-month" title="@item.ShortDescription">
                                    <span>@item.DtDay</span>
                                    @if (item.HasEvent)
                                    {
                                        <img src="~/Bundle/img/Group 226.png" />
                                        <p class="ellipsis">@item.ShortDescription</p>
                                    }
                                </li>
                            }
                            else
                            {
                                <li title="@item.ShortDescription">
                                    <span>@item.DtDay</span>
                                    @if (item.HasEvent)
                                    {
                                        <img src="~/Bundle/img/Group 226.png" />
                                        <p class="ellipsis">@item.ShortDescription</p>
                                    }
                                </li>
                            }
                        }
                        else
                        {
                            <li></li>
                        }
                    }
                }
            </ul>
        </div>
    </div>
</div>
<a onclick="loadCalendar('@Model.PrevMonth', '@ViewBag.Id')">
    <img class="calendar-prev" src="~/Bundle/img/Subtraction 2.png" alt="">
</a>
<a onclick="loadCalendar('@Model.NextMonth', '@ViewBag.Id')">
    <img class="calendar-next" src="~/Bundle/img/Subtraction 1.png" alt="">
</a>

MyEventCalendar/Views/Event/ShowEvent.cshtml
@using MyEventCalendar.Models
@model IEnumerable<EventModel>
<div class="panel panel-primary">
    <div class="panel-heading panel-head">Events</div>
    <div class="panel-body">
        <div class="btn-group">
            <a id="createEditStudentModal" data-toggle="modal" href="@Url.Action("AddEditEvent")" data-target="#modal-action-student" class="btn btn-primary">
                <i class="glyphicon glyphicon-plus"></i>  Add Event
            </a>
        </div>
        <div class="top-buffer"></div>
        <table class="table table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Short Description</th>
                    <th>Long Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ID</td>
                        <td>
                            @if (item.Date != null)
                            {
                                @item.Date.Date.ToShortDateString()
                            }
                        </td>
                        <td>@item.ShortDescription</td>
                        <td>@item.LongDescription</td>
                        <td>
                            <a id="editUserModal" data-toggle="modal" href="@Url.Action("AddEditEvent", new {id=item.ID })" data-target="#modal-action-student" class="btn btn-info">
                                <i class="glyphicon glyphicon-pencil"></i>  Edit
                            </a>
                            <a id="deleteUserModal" data-toggle="modal" href="@Url.Action("DeleteEvent", new {id=item.ID })" data-target="#modal-action-student" class="btn btn-danger">
                                <i class="glyphicon glyphicon-trash"></i>  Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-student", AreaLabeledId = "modal-action-student-label", Size = ModalSize.Medium })
@section scripts{
    @Scripts.Render("~/Scripts/event.js")
}

MyEventCalendar/Views/Event/_AddEditEvent.cshtml
@using MyEventCalendar.Models
@model EventModel

@using (Html.BeginForm())
{
    @Html.Partial("_ModalHeader", new ModalHeader { Heading = $"{(@Model.ID == 0 ? "Add" : "Edit")} Student"})
    <div class="modal-body form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { @class = "col-lg-3 col-sm-3 control-label" })
            <div class="col-lg-6">
                @Html.TextBoxFor(model => model.Date, new { @class = "form-control ", type="date" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, new { @class = "col-lg-3 col-sm-3 control-label" })
            <div class="col-lg-6">
                @Html.TextBoxFor(model => model.ShortDescription, new { @class = "form-control " })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LongDescription, new { @class = "col-lg-3 col-sm-3 control-label" })
            <div class="col-lg-6">
                @Html.TextBoxFor(model => model.LongDescription, new { @class = "form-control " })
            </div>
        </div>
    </div>
    @Html.Partial("_ModalFooter", new ModalFooter { })
}

MyEventCalendar/Views/Event/_DeleteEvent.cshtml
@model EventModel
@using MyEventCalendar.Models
@using (Html.BeginForm())
{
    @Html.Partial("_ModalHeader", new ModalHeader { Heading = "Delete Event" })

    <div class="modal-body form-horizontal">
        Are you want to delete @Model.ShortDescription?
    </div>
    @Html.Partial("_ModalFooter", new ModalFooter { SubmitButtonText="Delete"})
}

MyEventCalendar/Views/Shared/_CalendarLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Minor</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Import Css here -->
    <link rel="stylesheet" href="/Bundle/vendor/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="/Bundle/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/Bundle/vendor/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="/Bundle/vendor/owlcarousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="/Bundle/vendor/owlcarousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="/Bundle/vendor/wow/animate.min.css">
    <link rel="stylesheet" href="/Bundle/Css/style.min.css">
    <!-- End Import Css -->
</head>
<body>
    @RenderBody()
    <!-- Import Script here -->
    <script src="/Bundle/vendor/jquery/jquery-3.3.1.min.js"></script>
    <script src="/Bundle/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/Bundle/vendor/owlcarousel/owl.carousel.min.js"></script>
    <script src="/Bundle/vendor/wow/wow.min.js"></script>
    <script src="/Bundle/vendor/counterup/jquery.waypoints.min.js"></script>
    <script src="/Bundle/vendor/counterup/jquery.counterup.min.js"></script>
    <script src="/Bundle/js/app.min.js"></script>
    @*<script src="/Bundle/js/site.js"></script>*@
    <!-- End Import Script -->
</body>
</html>

MyEventCalendar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event Calendar</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery","~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Calendar", "Index", "Calendar", new { area = "" }, new { @class = "navbar-brand" })
        </div>          
    </div>
</div>
<div class="container body-content top-buffer">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - ASP.NET MVC Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

MyEventCalendar/Views/Shared/_Modal.cshtml
@model MyEventCalendar.Models.BootstrapModel

<div aria-hidden="true" aria-labelledby="@Model.AreaLabeledId" role="dialog" tabindex="-1" id="@Model.ID" class="modal fade">
    <div class="modal-dialog @Model.ModalSizeClass">
        <div class="modal-content">
        </div>
    </div>
</div>

MyEventCalendar/Views/Shared/_ModalFooter.cshtml
@model MyEventCalendar.Models.ModalFooter
<div class="modal-footer">
    <button data-dismiss="modal" id="@Model.CancelButtonID" class="btn btn-default" type="button">@Model.CancelButtonText</button>
    @if (!Model.OnlyCancelButton)
    {
        <button class="btn btn-success" id="@Model.SubmitButtonID" type="submit">            
            @Model.SubmitButtonText</button>
    }
</div>

MyEventCalendar/Views/Shared/_ModalHeader.cshtml
@model MyEventCalendar.Models.ModalHeader
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">@Model.Heading</h4>
</div>